### ISSUE TITLE
Support OSX split-fullscreen for helper window

### ISSUE THREAD

**Issue by owickstrom** [mpflanzer/splitshow#53] opened 2017-02-15 07:18 UTC
I usually split my screen, vim + Preview. The problem is that the PDF with both slides and notes become very wide, and thus the notes are hard to read. Ideally, I would see only the notes when editing. So I thought I could use the helper window in SplitShow while editing, but it does not support OSX fullscreen splits. Could that be supported? I know basically nothing about writing OSX desktop apps, so not sure if I'm a good candidate for implementing this. :)

**Comment by mpflanzer** [comment] 2017-02-15 21:08
That was easy. ;) This commit introduces the ability to split fullscreen windows: https://github.com/mpflanzer/splitshow/commit/3e191c788c340a6c11c90de21ffc4e0a92194499

I guess if you're using SplitShow for preview during edit it would also be handy if the presentation would refresh automatically? (If I remember correctly, that's still something I need to implement).

Do you usually build SplitShow yourself? Otherwise I will create a new release.

**Comment by owickstrom** [comment] 2017-02-15 21:11
Wow, that was fast! :) Yep, refresh would be very nice. The Preview app in macOS has reload _when you focus the window_, but it would be even better if SplitShow could reload even if unfocused.

I haven't built it myself yet, but I can try! Downloading XCode now. 😄 Then maybe I can contribute something back one day.

**Comment by owickstrom** [comment] 2017-02-15 21:23
I managed to build it myself. 👍 

Found this, though:

![image](https://cloud.githubusercontent.com/assets/1464328/22995959/3be38eee-f3cd-11e6-94e9-836cb62dab14.png)

The timer ends up in the vertical center of the helper display when in fullscreen tiled.

**Comment by owickstrom** [comment] 2017-02-15 21:31
Also, it focuses back on the main screen each time I change slides.

**Comment by mpflanzer** [comment] 2017-02-15 22:47
Yeah, I know that the timer sometimes behaves a bit "strange". I am already working on a better solution.
What do you mean by "change slides"? Going back and forth or changing them in vim? Anyway I will take a look tomorrow. Thanks for testing.

**Comment by owickstrom** [comment] 2017-02-16 06:15
> What do you mean by "change slides"? Going back and forth or changing them in vim? And what is "the main screen"? The one from SplitShow?

Sorry, I was unclear. Going back and forth between slides, in the helper window (tiled in fullscreen). I get navigated back to the main window of SplitShow (not tiled, on default desktop) as soon as I navigate in the helper window.

These may not be new things related to the tiling fullscreen support, so no pressure! :) I'm just glad this project is alive and kicking, as I'm using it.

**Comment by mpflanzer** [comment] 2017-02-16 20:46
I was able to reproduce the behaviour although not exactly as you describe. For me the switch back to the main window only happens if I, sticking with your use case, switch from SplitShow to vim and then back again. As soon as I click on the SplitShow screen (or use cmd + Tab) to get back from vim to SplitShow it will navigate to the main window.

That is indeed a problem that existed before. But with the split screen it is more likely to be noticed. The problem is that the main screen is indeed the main screen of the program and when bringing the focus back to SplitShow macOS always seems to switch to the main window, not the last viewed one.

I'm not yet sure how to solve that. It might take a bit longer than the split screen support. ;) I will open a new issue for that problem and close this one as split screen is technically working now.

Feel free to reopen if I missed something.

**Closed by mpflanzer** 2017-02-16 20:46 UTC
Labels: enhancement

**Comment by owickstrom** [comment] 2017-02-16 20:56
Sounds good, thanks! :)
