### ISSUE TITLE
SplitShow creates two spaces on presentation but presentation of main screen is on first space "desktop" not the new generated space...

### ISSUE THREAD

**Issue by novski** [mpflanzer/splitshow#49] opened 2016-11-24 08:33 UTC
macOS Sierra 10.12.1 

What i did:
Installed Splitshow and started the SplitShowDemo.pdf
Conected a VGA Beamer.
Set Splitshow to mirror and configured the first and second screen. Then pressed start presentation.

What i expected to hapen:
To see the same page of the PDF on my Laptop and my Beamer
What i got to see:
Beamer shows SplitShowDemo.pdf page 1 and Laptop screen goes black.

What i found:
SplitShow creates new spaces for each Display and the Beamer space gets shown correctly.
The new space of my Laptop Display is Black and the SplitShow Window is on the already existed space called desktop. When pressing stop presentation both spaces are gone.

What i recomend:
There are several options for arranging spaces in systemconfig/mission controll.
Test with different options but in my tests the drop down for dashboard has no influence...

**Comment by mpflanzer** [comment] 2016-11-26 10:31
Thanks for reporting this. This is indeed worrying.
I will try to fix it as soon as possible.

**Comment by mpflanzer** [comment] 2016-11-28 17:19
Haven't found the actual issue yet but I can confirm that it only happens with macOS Sierra. Previous systems are not affected.

**Comment by mpflanzer** [comment] 2016-11-28 21:21
Should be fixed in the latest release and master branch. Could you please test again?

**Comment by novski** [comment] 2016-11-30 09:01
It doesn't work yet.
I have several spaces active and start the SplitShow from space 3. It then is configured to mirror and the left and right are set to unknown (what generates a new space) and i hit start presentation then it generates 2 spaces and for 1 second i see the presentation on both but then always the one with the counter in the left lower corner goes away. So the right display stays correctly as chosen but the left display comes up for 1 second and goes back to space 3 as a window leaving the generated space black.

**Comment by mpflanzer** [comment] 2016-12-03 09:43
Sorry, I can't reproduce it anymore. Are you sure you are using the latest released version: https://github.com/mpflanzer/splitshow/releases/tag/0.9.8-alpha3? In the menu bar "SplitShow" -> "About SplitShow" the version has to be 0.9.8 (4).

Or I am doing not exactly was you are trying. What do you mean by "the left and right are set to unknown"? The drop down menus should show the options "No display", "New window" (which just creates two non-fullscreen windows), and the names of all connected monitors. Are your monitors shown as "unknown"?

If you can't get it working the current work around would be to select "New window" for both monitors. After starting the presentation you can manually activate the fullscreen mode for both windows.

**Comment by novski** [comment] 2017-03-31 07:15
sorry it seams i missed that. It works now for me.
As i just read in a different [issue](https://github.com/mpflanzer/splitshow/issues/54) the Display names don't get displayed. Thats what i wanted to say with unknown on left and right. 
you can close this one...

**Closed** 2017-05-01 15:33 UTC
Labels: bug, high
